server:
  port: 8080

spring:
  mvc:
    format:
      date: dd-MM-yyyy
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:rewardprogram;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: "/h2"
